### ISSUE TITLE
Arsenal is busted

### ISSUE THREAD

**Issue by Gluttony13th** [matthawkins2/ParamarineTaskForce#6]
Doesn't have any of my loadouts.

**Comment by EMurry** [comment]
Needs Kitbag - Green (for Corpsmen)

**Comment by bertyhell** [comment]
Also, the RCO and ARCO scopes if those are permitted.

The only scope in the arsenal that currently can switch between holographic/3x is the SU230A / PVS MRDS. But that one has 4 states where 2 are not very useful. The RCO and ARCO only have 2 states and both are useful.

https://steamcommunity.com/sharedfiles/filedetails/?id=416741360#584319
![image](https://user-images.githubusercontent.com/1710840/48306595-acd0db00-e53b-11e8-886d-590f01cf0b17.png)
![image](https://user-images.githubusercontent.com/1710840/48306599-af333500-e53b-11e8-9a7a-9bc092de8734.png)
